-- local null_ls = require("null-ls")
--
-- null_ls.setup({
--     sources = {
--         null_ls.builtins.formatting.prettier,
--         null_ls.builtins.formatting.stylelint,
--         null_ls.builtins.diagnostics.eslint,
--         null_ls.builtins.diagnostics.stylelint
--     },
-- })
--
-- vim.cmd[[autocmd BufWritePre * :lua vim.lsp.buf.format()]]
